module.exports = [
  {
    id: 1,
    title: "hi",
    categoryId: 1,
    createdAt: "",
    updatedAt: "",
    viewNum: 12,
    content: "hihihi",
    authorId: 1,
    thumbnailId: 3,
  },
  {
    id: 2,
    title: "hi",
    categoryId: 1,
    createdAt: "",
    updatedAt: "",
    viewNum: 12,
    content: "hihihi",
    authorId: 1,
    thumbnailId: 3,
  },
  {
    id: 3,
    title: "hi",
    categoryId: 1,
    createdAt: "",
    updatedAt: "",
    viewNum: 12,
    content: "hihihi",
    authorId: 1,
    thumbnailId: 3,
  },
  {
    id: 4,
    title: "hi",
    categoryId: 1,
    createdAt: "",
    updatedAt: "",
    viewNum: 12,
    content: "hihihi",
    authorId: 1,
    thumbnailId: 3,
  },
];
